public import Foundation

/// Единственное место, где живут строки интерфейса.
///
/// Лежит отдельно от `Strings` намеренно: поиск по ключу — это код,
/// а таблица — данные, и растут они с разной скоростью.
extension Strings {
    static let table: [String: [Language: String]] = [
        // Настройки, темы, подвал и общие кнопки
        "set.motion": [.russian: "движение", .english: "motion"],
        "motion.full": [.russian: "полностью", .english: "full"],
        "motion.brief": [.russian: "короче", .english: "brief"],
        "motion.off": [.russian: "выключить", .english: "off"],
        "set.connectMotion": [.russian: "подключение к хосту", .english: "connecting to a host"],
        "motion.sweep": [.russian: "луч по строке", .english: "a sweep along the row"],
        "motion.arc": [.russian: "дуга проверки", .english: "a checking arc"],
        "motion.none": [.russian: "без движения", .english: "no motion"],
        "set.logMotion": [.russian: "приход строки лога", .english: "a log line arriving"],
        "motion.rise": [.russian: "подъём", .english: "rise"],
        "motion.fade": [.russian: "проявление", .english: "fade in"],
        "set.motionNote": [
            .russian:
                "движутся положение и прозрачность, больше ничего. При системной «уменьшить движение» сразу показывается конечный кадр.",
            .english:
                "position and opacity move, nothing else. With the system Reduce Motion on, the final frame shows at once.",
        ],
        "menu.connect": [.russian: "подключиться", .english: "connect"],
        "menu.files": [.russian: "файлы", .english: "files"],
        "menu.edit": [.russian: "править…", .english: "edit…"],
        "menu.duplicate": [.russian: "дублировать", .english: "duplicate"],
        "auth.reason": [.russian: "открыть профиль Phosphor", .english: "open the Phosphor profile"],
        "auth.saveReason": [.russian: "сохранить профиль Phosphor", .english: "save the Phosphor profile"],
        "auth.unavailable": [.russian: "проверка недоступна:", .english: "verification unavailable:"],
        "auth.lockedOut": [
            .russian: "биометрия заблокирована — войди паролем учётной записи",
            .english: "biometrics are locked out — use your account password",
        ],
        "auth.cancelled": [.russian: "вход отменён", .english: "unlock cancelled"],
        "vault.keyLost": [
            .russian: "профиль на месте, но ключ утерян — восстанови из экспорта",
            .english: "the profile is here but its key is gone — restore from an export",
        ],
        "vault.unreadable": [.russian: "профиль не читается:", .english: "the profile cannot be read:"],
        "bridge.locked": [
            .russian: "Phosphor заблокирован — приложи палец",
            .english: "Phosphor is locked — touch the sensor",
        ],
        "bridge.failed": [.russian: "мост не поднялся:", .english: "the bridge did not come up:"],
        "err.noSession": [.russian: "нет подключения к хосту", .english: "not connected to a host"],
        "err.inspectSilent": [
            .russian: "docker inspect не ответил", .english: "docker inspect said nothing",
        ],
        "dock.noEnv": [.russian: "у контейнера нет переменных", .english: "the container has no variables"],
        "fwd.needLink": [
            .russian: "нет живого соединения с хостом — подключись сначала",
            .english: "no live connection to the host — connect first",
        ],
        "host.copySuffix": [.russian: " копия", .english: " copy"],
        "files.server": [.russian: "сервер", .english: "server"],
        "files.cannotRead": [.russian: "не удалось прочитать", .english: "could not read"],
        "known.missing": [
            .russian: "файл ~/.ssh/known_hosts не найден — ты ещё никому не доверился",
            .english: "~/.ssh/known_hosts is not there — you have not trusted anyone yet",
        ],
        "known.writeFailed": [
            .russian: "не удалось записать known_hosts:", .english: "could not write known_hosts:",
        ],
        "mcp.mode": [.russian: "режим доступа:", .english: "access mode:"],
        "keys.readFailed": [
            .russian: "не удалось прочитать authorized_keys:", .english: "could not read authorized_keys:",
        ],
        "keys.noHost": [.russian: "хост не выбран", .english: "no host selected"],
        "keys.addFailed": [.russian: "не удалось добавить ключ:", .english: "could not add the key:"],
        "keys.lastKey": [
            .russian: "после удаления не останется ни одного рабочего ключа",
            .english: "removing this leaves no working key behind",
        ],
        "snip.noLink": [.russian: "не удалось подключиться", .english: "could not connect"],
        "common.empty": [.russian: "(пусто)", .english: "(nothing)"],
        "theme.needsSixteen": [
            .russian: "в файле нет всех шестнадцати цветов ANSI",
            .english: "the file does not carry all sixteen ANSI colours",
        ],
        "theme.added": [.russian: "добавлена тема", .english: "theme added"],
        "theme.unreadable": [.russian: "файл не читается:", .english: "the file cannot be read:"],
        "alert.removeKeyBodyShort": [
            .russian: "после этого войти можно будет только другим ключом",
            .english: "after this only another key will get you in",
        ],
        // Мониторинг и Docker
        "keys.pickNote": [
            .russian: "ключи читаются с сервера — выбери, с какого",
            .english: "keys are read from the server — pick which one",
        ],
        "keys.local": [.russian: "ключи на этой машине", .english: "keys on this Mac"],
        "keys.noPairs": [.russian: "в ~/.ssh нет пар ключей", .english: "no key pairs in ~/.ssh"],
        "keys.noPrivate": [.russian: "нет приватной", .english: "no private half"],
        "keys.copyPrint": [.russian: "копировать отпечаток", .english: "copy fingerprint"],
        "common.refresh": [.russian: "обновить", .english: "refresh"],
        "keys.key": [.russian: "ключ", .english: "key"],
        "keys.fingerprint": [.russian: "отпечаток", .english: "fingerprint"],
        "keys.options": [.russian: "опции", .english: "options"],
        "keys.pasteHint": [
            .russian: "вставь строку из id_ed25519.pub", .english: "paste a line from id_ed25519.pub",
        ],
        "keys.addToServer": [.russian: "добавить на сервер", .english: "add to the server"],
        "known.host": [.russian: "хост", .english: "host"],
        "known.type": [.russian: "тип", .english: "type"],
        "known.note": [
            .russian:
                "отпечатки считаются здесь, ssh-keygen для этого не нужен. «Забыть» удаляет строку: следующее подключение спросит доверие заново",
            .english:
                "computed here, on this Mac — no ssh-keygen needed. Forgetting the line makes the next connection ask again",
        ],
        "known.forget": [.russian: "забыть", .english: "forget"],
        "prov.pickNote": [
            .russian: "рецепт выполняется на сервере — выбери, на каком",
            .english: "the recipe runs on a server — pick which one",
        ],
        "prov.recipe": [.russian: "рецепт · базовый", .english: "recipe · baseline"],
        "prov.stopAfter": [.russian: "остановить после шага", .english: "stop after this step"],
        "prov.guard": [
            .russian:
                "шаг «закрыть вход по паролю» выполнится только после того, как отдельное соединение по ключу успешно откроется",
            .english:
                "the step that disables password login runs only after a separate key-based connection has opened",
        ],
        "prov.idempotent": [
            .russian: "идемпотентно, установленное пропускается",
            .english: "idempotent, anything already in place is skipped",
        ],
        "prov.liveLog": [.russian: "живой лог", .english: "live log"],
        "prov.log": [.russian: "лог", .english: "log"],
        "common.whatGoes": [.russian: "что уйдёт на сервер", .english: "what goes to the server"],
        "common.close": [.russian: "закрыть", .english: "close"],
        "act.tools": [.russian: "инструменты", .english: "tools"],
        "act.toolsNote": [
            .russian:
                "каждый инструмент — это дверь в твою инфраструктуру, поэтому список закрытый и короткий",
            .english:
                "every tool is a door into your infrastructure, which is why the list is closed and short",
        ],
        "act.what": [.russian: "что делает", .english: "what it does"],
        "act.class": [.russian: "класс", .english: "class"],
        "act.write": [.russian: "запись", .english: "write"],
        "act.read": [.russian: "чтение", .english: "read"],
        "act.perHost": [.russian: "доступ по хостам", .english: "access per host"],
        "act.newHostOff": [
            .russian: "новый хост выключен: забыть настроить не значит открыть",
            .english: "a new host is off: forgetting to set it up never means opening it",
        ],
        "act.howToConnect": [.russian: "как подключить клиента", .english: "how to register a client"],
        "act.bridgeUp": [
            .russian: "мост поднят, пока открыто приложение",
            .english: "the bridge is up while the app is open",
        ],
        "act.denyNote": [
            .russian: "запрещённые команды отклоняются в любом режиме, включая полный",
            .english: "denied commands are refused in every mode, full included",
        ],
        "act.journal": [.russian: "журнал действий", .english: "action log"],
        "act.appendOnly": [
            .russian: "только дозапись · инструмента для правки не существует",
            .english: "append only · no tool exists that can edit it",
        ],
        "act.empty": [.russian: "пока ничего не происходило", .english: "nothing has happened yet"],
        "clog.title": [.russian: "журнал подключений", .english: "connection log"],
        "clog.records": [.russian: "записей", .english: "records"],
        "clog.empty": [.russian: "подключений ещё не было", .english: "no connections yet"],
        "clog.note": [
            .russian:
                "только факт соединения. Содержимое сессий сюда не попадает: скроллбэк по умолчанию вообще не пишется на диск, и журнал не должен это обходить",
            .english:
                "the fact of a connection, nothing more. Session content never lands here, and this log must not work around that",
        ],
        "res.created": [.russian: "создан", .english: "created"],
        "res.size": [.russian: "размер", .english: "size"],
        "res.dangling": [.russian: "занимает место зря", .english: "taking space for nothing"],
        "res.copyID": [.russian: "копировать id", .english: "copy id"],
        "res.removeImage": [.russian: "удалить образ", .english: "remove image"],
        "res.volume": [.russian: "том", .english: "volume"],
        "res.driver": [.russian: "драйвер", .english: "driver"],
        "res.mount": [.russian: "точка монтирования", .english: "mount point"],
        "res.copyPath": [.russian: "копировать путь", .english: "copy path"],
        "res.removeVolume": [.russian: "удалить том", .english: "remove volume"],
        "res.network": [.russian: "сеть", .english: "network"],
        "res.scope": [.russian: "область", .english: "scope"],
        "res.removeNetwork": [.russian: "удалить сеть", .english: "remove network"],
        "term.remember": [.russian: "запомнить", .english: "remember"],
        "term.nope": [.russian: "не надо", .english: "no thanks"],
        "term.connecting": [.russian: "подключаюсь…", .english: "connecting…"],
        "term.probing": [.russian: "собираю профиль хоста…", .english: "building the host profile…"],
        "term.uptime": [.russian: "аптайм", .english: "uptime"],
        "term.clipboard": [
            .russian: "сервер хочет записать в буфер обмена",
            .english: "the server wants to write to the clipboard",
        ],
        "term.oddLink": [.russian: "ссылка с необычной схемой", .english: "a link with an unusual scheme"],
        "term.spaces": [.russian: "спейсы", .english: "spaces"],
        "term.noSpaces": [
            .russian: "нет открытых спейсов — нажми + и подключись к серверу",
            .english: "no open spaces — press + and connect to a server",
        ],
        "term.sessions": [.russian: "сессии", .english: "sessions"],
        "term.closeSpace": [.russian: "убрать спейс", .english: "close space"],
        "term.persist": [.russian: "постоянные сессии", .english: "persistent sessions"],
        "term.sessionName": [.russian: "имя сессии", .english: "session name"],
        "term.killSession": [.russian: "снять сессию на сервере", .english: "kill session on server"],
        "term.window": [.russian: "окно", .english: "window"],
        "term.windows": [.russian: "окон", .english: "windows"],
        "hosts.known": [.russian: "известные хосты", .english: "known hosts"],
        "hosts.termius": [.russian: "история Termius", .english: "Termius history"],
        "hosts.noNew": [.russian: "новых нет", .english: "nothing new"],
        "hosts.added": [.russian: "добавлено", .english: "added"],
        "hosts.skipped": [.russian: "не распознано", .english: "not recognised"],
        "hosts.recent": [.russian: "последние", .english: "recent"],
        "hosts.saved": [.russian: "сохранён", .english: "saved"],
        "hosts.notSaved": [.russian: "не сохранён", .english: "not saved"],
        "hosts.remember": [.russian: "запомнить", .english: "remember"],
        "host.direct": [.russian: "напрямую", .english: "direct"],
        "host.viaProxy": [.russian: "через прокси", .english: "through a proxy"],
        "host.new": [.russian: "новый хост", .english: "new host"],
        "host.edit": [.russian: "правка хоста", .english: "edit host"],
        "host.address": [.russian: "адрес", .english: "address"],
        "host.addressHint": [.russian: "10.0.0.1 или example.com", .english: "10.0.0.1 or example.com"],
        "host.user": [.russian: "пользователь", .english: "user"],
        "host.port": [.russian: "порт", .english: "port"],
        "host.name": [.russian: "имя", .english: "name"],
        "host.nameHint": [
            .russian: "необязательно — возьмём адрес", .english: "optional — the address will do",
        ],
        "host.tags": [.russian: "теги", .english: "tags"],
        "host.tagsHint": [.russian: "через запятую", .english: "comma separated"],
        "common.add": [.russian: "добавить", .english: "add"],
        "common.save": [.russian: "сохранить", .english: "save"],
        "host.groupNote": [
            .russian: "группа — она несёт настройки: доступ, тему, режим ии",
            .english: "the group carries the settings: how to reach it, the theme, what the model may do",
        ],
        "host.noGroup": [.russian: "без группы", .english: "no group"],
        "host.reach": [.russian: "как дотянуться", .english: "how to reach it"],
        "host.proxyHost": [.russian: "хост прокси", .english: "proxy host"],
        "group.new": [.russian: "новая группа", .english: "new group"],
        "group.rename": [.russian: "переименовать группу", .english: "rename group"],
        "group.hint": [.russian: "прод, стейдж, домашние…", .english: "production, staging, home…"],
        "snip.title": [.russian: "сниппеты", .english: "snippets"],
        "snip.new": [.russian: "новый", .english: "new"],
        "snip.name": [.russian: "название", .english: "name"],
        "snip.substitutions": [.russian: "подстановки", .english: "placeholders"],
        "snip.whatGoes": [.russian: "что уйдёт на сервер", .english: "what goes to the server"],
        "snip.runHere": [.russian: "выполнить здесь", .english: "run here"],
        "snip.runAll": [.russian: "на всех в", .english: "on every host in"],
        "snip.output": [.russian: "вывод", .english: "output"],
        "snip.empty": [.russian: "сниппетов ещё нет", .english: "no snippets yet"],
        "fwd.title": [.russian: "проброс портов", .english: "port forwards"],
        "fwd.noHost": [
            .russian: "хост не выбран — пробросы привязаны к хосту",
            .english: "no host selected — forwards belong to a host",
        ],
        "fwd.empty": [.russian: "пока ничего не проброшено", .english: "nothing forwarded yet"],
        "fwd.note": [
            .russian:
                "локальный слушает только на 127.0.0.1: пробросить порт и открыть его всей сети — обидная ошибка, и по умолчанию её быть не должно",
            .english:
                "a local forward listens on 127.0.0.1 only: opening it to the whole network is an expensive slip, never a default",
        ],
        "fwd.direction": [.russian: "направление", .english: "direction"],
        "fwd.localPort": [.russian: "порт у себя", .english: "port here"],
        "fwd.remoteHost": [.russian: "куда, хост", .english: "to host"],
        "fwd.remotePort": [.russian: "куда, порт", .english: "to port"],
        "fwd.onConnect": [.russian: "при подключении", .english: "on connect"],
        "fwd.down": [.russian: "опустить", .english: "take down"],
        "fwd.up": [.russian: "поднять", .english: "bring up"],
        "files.local": [.russian: "локально", .english: "local"],
        "files.noLink": [.russian: "нет подключения", .english: "not connected"],
        "files.pickOnHosts": [
            .russian: "выбери хост на вкладке «хосты»", .english: "pick a host on the Hosts tab",
        ],
        "files.sameSSH": [.russian: "то же ssh-соединение", .english: "the same ssh connection"],
        "files.modified": [.russian: "изменён", .english: "modified"],
        "files.size": [.russian: "размер", .english: "size"],
        "files.note": [
            .russian:
                "файлы идут по тому же соединению, что и терминал: отдельного логина нет, и через тот же прокси или бастион",
            .english:
                "files ride the connection the terminal holds: no second login, same proxy or bastion",
        ],
        "mon.pickNote": [
            .russian: "снимки /proc идут по тому же соединению — выбери сервер",
            .english: "/proc snapshots ride the same connection — pick a server",
        ],
        "mon.topProcesses": [.russian: "самые тяжёлые процессы", .english: "heaviest processes"],
        "mon.command": [.russian: "команда", .english: "command"],
        "mon.memory": [.russian: "память", .english: "memory"],
        "mon.noData": [.russian: "нет данных — подключись к хосту", .english: "no data — connect to a host"],
        "mon.uptime": [.russian: "аптайм", .english: "uptime"],
        "mon.processes": [.russian: "процессы", .english: "processes"],
        "mon.handles": [.russian: "дескрипторы", .english: "handles"],
        "mon.containers": [.russian: "контейнеры", .english: "containers"],
        "mon.noLink": [.russian: "нет соединения", .english: "not connected"],
        "mon.secondSnapshot": [
            .russian: "ждём второго снимка: загрузка — это разница",
            .english: "waiting for the second snapshot: load is a difference",
        ],
        "mon.diskIO": [.russian: "диск: чтение и запись", .english: "disk: reads and writes"],
        "mon.noSwap": [.russian: "swap отсутствует", .english: "no swap"],
        "dock.noHost": [.russian: "сервер не выбран", .english: "no server selected"],
        "dock.connecting": [.russian: "подключаюсь…", .english: "connecting…"],
        "dock.pickNote": [
            .russian: "docker читается по тому же соединению — выбери сервер",
            .english: "docker is read over the same connection — pick a server",
        ],
        "dock.pickShort": [.russian: "выбери сервер", .english: "pick a server"],
        "dock.noLogs": [.russian: "логов пока нет", .english: "no log lines yet"],
        "dock.image": [.russian: "образ", .english: "image"],
        "dock.state": [.russian: "состояние", .english: "state"],
        "dock.status": [.russian: "статус", .english: "status"],
        "dock.ports": [.russian: "порты", .english: "ports"],
        "dock.noPorts": [.russian: "не опубликованы", .english: "none published"],
        "dock.stack": [.russian: "стек", .english: "stack"],
        "dock.noStack": [.russian: "вне стека", .english: "no stack"],
        "dock.undeclared": [.russian: "не объявлен", .english: "not declared"],
        "dock.limitShare": [.russian: "доля лимита", .english: "share of limit"],
        "dock.processCount": [.russian: "процессов", .english: "processes"],
        "dock.host": [.russian: "хост", .english: "host"],
        "common.of": [.russian: "из", .english: "of"],
        "common.perSec": [.russian: "/с", .english: "/s"],
        "mon.sick": [.russian: "больных", .english: "unhealthy"],
        "mon.free": [.russian: "свободно", .english: "free"],
        "mon.kernel": [.russian: "ядро", .english: "kernel"],
        "dock.exposed": [
            .russian: "порт открыт наружу мимо UFW: ", .english: "a port is exposed past UFW: ",
        ],
        "alert.removeHost": [
            .russian: "из списка, но не с сервера: сам сервер останется на месте",
            .english: "from the list, not from the world: the server itself stays where it is",
        ],
        "alert.removeKeyTitle": [
            .russian: "удалить ключ, которым ты подключён?",
            .english: "remove the key you are connected with?",
        ],
        "alert.removeKeyBody": [
            .russian: "после этого войти можно будет только другим ключом",
            .english: "after this only another key will get you in",
        ],
        "alert.mcpAsks": [.russian: "ии просит выполнить на", .english: "the model asks to run on"],
        "set.palette": [.russian: "палитра ansi", .english: "ansi palette"],
        "set.import": [.russian: "импорт .itermcolors", .english: "import .itermcolors"],
        "set.special": [.russian: "особые цвета", .english: "special colours"],
        "set.text": [.russian: "текст", .english: "text"],
        "set.bg": [.russian: "фон", .english: "background"],
        "set.cursor": [.russian: "курсор", .english: "cursor"],
        "set.selection": [.russian: "выделение", .english: "selection"],
        "set.font": [.russian: "шрифт", .english: "font"],
        "set.size": [.russian: "размер", .english: "size"],
        "set.pt": [.russian: "пт", .english: "pt"],
        "set.ligatures": [.russian: "лигатуры", .english: "ligatures"],
        "set.lineHeight": [.russian: "строка", .english: "line"],
        "set.fontNote": [
            .russian: "IBM Plex Mono едет в бандле — на систему не полагаемся",
            .english: "IBM Plex Mono ships in the bundle — nothing is expected from the system",
        ],
        "set.glassNote": [
            .russian:
                "скан-линии и виньетка рисуются один раз и не стоят ничего на кадр: это не анимация, а статичный слой",
            .english:
                "scanlines and the vignette are drawn once and cost nothing per frame: a static layer, not an animation",
        ],
        "set.pet": [.russian: "питомец", .english: "pet"],
        "set.off": [.russian: "выключить", .english: "turn off"],
        "set.petNote": [
            .russian: "на продовых хостах питомца нет по умолчанию — на проде не играют",
            .english: "production hosts have no pet by default — nobody plays on production",
        ],
        "set.poll": [.russian: "опрос сервера", .english: "server polling"],
        "set.interval": [.russian: "интервал", .english: "interval"],
        "set.sec": [.russian: "с", .english: "s"],
        "set.pollNote": [
            .russian:
                "опрос замирает, когда окно не на виду: интервал — это про то, как часто спрашивать, пока смотришь",
            .english:
                "polling stops when the window is out of sight: the interval is how often to ask while you are looking",
        ],
        "set.logBuffer": [.russian: "буфер логов контейнера", .english: "container log buffer"],
        "set.logNote": [
            .russian: "буфер ограничен сверху всегда: неограниченный — это утечка с отложенным сроком",
            .english: "every buffer has a ceiling: an unbounded one is a leak with a delayed due date",
        ],
        "set.showEggs": [.russian: "показывать отсылки", .english: "show references"],
        "set.eggsNote": [
            .russian:
                "отсылка никогда не подменяет информацию: значок стоит рядом с настоящим числом, а не вместо него",
            .english:
                "a reference never replaces information: the badge sits next to the real number, never instead of it",
        ],
        "set.binding": [.russian: "привязка", .english: "bound to"],
        "set.default": [.russian: "по умолчанию", .english: "default"],
        "set.bindingNote": [
            .russian: "клик привязывает выбранную тему к группе",
            .english: "clicking binds the selected theme to a group",
        ],
        "set.glass": [.russian: "фон и стекло", .english: "background and glass"],
        "set.scanlines": [.russian: "скан-линии", .english: "scanlines"],
        "set.glow": [.russian: "свечение", .english: "glow"],
        "set.vignette": [.russian: "виньетка", .english: "vignette"],
        "set.resetGlass": [.russian: "вернуть как в теме", .english: "back to the theme's own"],
        "set.preview": [.russian: "предпросмотр", .english: "preview"],
        "theme.phosphor": [.russian: "Фосфор", .english: "Phosphor"],
        "theme.amber": [.russian: "Янтарь", .english: "Amber"],
        "theme.ice": [.russian: "Лёд", .english: "Ice"],
        "theme.ruby": [.russian: "Рубин · прод", .english: "Ruby · production"],
        "theme.glass": [.russian: "Стекло", .english: "Glass"],
        "foot.hosts": [.russian: "хостов", .english: "hosts"],
        "foot.groups": [.russian: "групп", .english: "groups"],
        "foot.catAsleep": [.russian: "котёнок спит", .english: "the cat is asleep"],
        "foot.gliderAsleep": [.russian: "поссум спит", .english: "the glider is asleep"],
        "common.cancel": [.russian: "отмена", .english: "cancel"],
        "common.delete": [.russian: "удалить", .english: "delete"],
        "common.allow": [.russian: "разрешить", .english: "allow"],
        "common.deny": [.russian: "отклонить", .english: "deny"],
        "common.addHost": [.russian: "+ добавить хост", .english: "+ add a host"],
        "common.noHosts": [.russian: "хостов пока нет", .english: "no hosts yet"],
        // Lock screen
        "lock.touch": [.russian: "приложи палец", .english: "touch to unlock"],
        "lock.reading": [.russian: "читаю отпечаток", .english: "reading fingerprint"],
        "lock.open": [.russian: "доступ открыт", .english: "access granted"],
        "lock.noAccount": [
            .russian: "ни логина, ни пароля. учётной записи нет — есть профиль на этой машине",
            .english: "no login, no password. there is no account — only a profile on this Mac",
        ],
        "lock.fallback": [
            .russian: "нет Touch ID? apple watch · пароль учётной записи",
            .english: "no Touch ID? apple watch · account password",
        ],
        "lock.locked": [.russian: "заблокировано", .english: "locked"],
        "lock.unlocked": [.russian: "открыто", .english: "unlocked"],
        "lock.vault": [
            .russian: "секреты не покидают Secure Enclave",
            .english: "secrets never leave the Secure Enclave",
        ],

        // Sections
        "nav.hosts": [.russian: "хосты", .english: "hosts"],
        "nav.keys": [.russian: "ключи", .english: "keys"],
        "nav.forwarding": [.russian: "проброс портов", .english: "port forwarding"],
        "nav.snippets": [.russian: "сниппеты", .english: "snippets"],
        "nav.known": [.russian: "известные хосты", .english: "known hosts"],
        "nav.log": [.russian: "журнал", .english: "log"],
        "nav.containers": [.russian: "контейнеры", .english: "containers"],
        "nav.images": [.russian: "образы", .english: "images"],
        "nav.volumes": [.russian: "тома", .english: "volumes"],
        "nav.networks": [.russian: "сети", .english: "networks"],
        "nav.overview": [.russian: "обзор", .english: "overview"],
        "nav.processes": [.russian: "процессы", .english: "processes"],
        "nav.storage": [.russian: "память и диски", .english: "memory and disks"],
        "nav.netStat": [.russian: "сеть", .english: "network"],
        "nav.journal": [.russian: "журнал", .english: "journal"],
        "nav.access": [.russian: "доступ", .english: "access"],
        "nav.tools": [.russian: "инструменты", .english: "tools"],
        "nav.palette": [.russian: "палитра", .english: "palette"],
        "nav.glass": [.russian: "стекло", .english: "glass"],
        "nav.language": [.russian: "язык и отсылки", .english: "language and eggs"],
        "nav.behaviour": [.russian: "поведение", .english: "behaviour"],

        // Tabs
        "tab.terminal": [.russian: "терминал", .english: "terminal"],
        "tab.docker": [.russian: "docker", .english: "docker"],
        "tab.files": [.russian: "файлы", .english: "files"],
        "tab.monitor": [.russian: "мониторинг", .english: "monitor"],
        "tab.theme": [.russian: "настройки", .english: "settings"],
        "tab.provision": [.russian: "автонастройка", .english: "provisioning"],
        "tab.activity": [.russian: "активность ии", .english: "ai activity"],

        // Hosts
        "hosts.search": [
            .russian: "найти хост, тег, группу или user@host…",
            .english: "find a host, tag, group or user@host…",
        ],
        "hosts.connect": [.russian: "подключиться", .english: "connect"],
        "hosts.new": [.russian: "+ новый хост", .english: "+ new host"],
        "hosts.import": [.russian: "импорт ~/.ssh/config", .english: "import ~/.ssh/config"],
        "hosts.groups": [.russian: "группы", .english: "groups"],
        "hosts.all": [.russian: "хосты", .english: "hosts"],
        "hosts.filterHint": [.russian: "нажми, чтобы отфильтровать", .english: "click to filter"],
        "hosts.clearFilter": [.russian: "нажми ещё раз — снять", .english: "click again to clear"],
        "hosts.empty": [.russian: "ничего не найдено", .english: "nothing found"],

        // Docker
        "docker.containers": [.russian: "контейнеры", .english: "containers"],
        "docker.logs": [.russian: "логи", .english: "logs"],
        "docker.overview": [.russian: "обзор", .english: "overview"],
        "docker.env": [.russian: "переменные", .english: "environment"],
        "docker.restart": [.russian: "перезапустить", .english: "restart"],
        "docker.stop": [.russian: "остановить", .english: "stop"],
        "docker.remove": [.russian: "удалить", .english: "remove"],
        "docker.secretsHidden": [
            .russian: "секреты замаскированы и не попадают в аудит",
            .english: "secrets are masked and never reach the audit log",
        ],

        // Monitor
        "monitor.cores": [.russian: "ядра", .english: "cores"],
        "monitor.memory": [.russian: "память", .english: "memory"],
        "monitor.disks": [.russian: "диски", .english: "disks"],
        "monitor.network": [.russian: "сеть", .english: "network"],
        "monitor.steal": [.russian: "сосед по гипервизору", .english: "noisy neighbour"],
        "monitor.uptime": [.russian: "аптайм", .english: "uptime"],

        // Keys
        "keys.yours": [.russian: "твой", .english: "yours"],
        "keys.current": [
            .russian: "этим ключом ты подключён сейчас", .english: "you are connected with this key",
        ],
        "keys.weak": [.russian: "слабый ключ", .english: "weak key"],
        "keys.lockout": [
            .russian: "удалить ключ, которым ты подключён, можно только с подтверждением",
            .english: "removing the key you are connected with needs explicit confirmation",
        ],

        // Provisioning
        "provision.fresh": [.russian: "свежий сервер", .english: "fresh server"],
        "provision.offer": [
            .russian: "сервер только что поднят и пуст. Настроить по обычному рецепту?",
            .english: "this server was just brought up and is empty. Run the usual recipe?",
        ],
        "provision.run": [.russian: "настроить", .english: "provision"],
        "provision.show": [.russian: "показать команды", .english: "show commands"],
        "provision.later": [.russian: "позже", .english: "later"],
        "provision.done": [.russian: "готово", .english: "done"],
        "provision.running": [.russian: "идёт", .english: "running"],
        "provision.waiting": [.russian: "ожидает", .english: "waiting"],
        "provision.skipped": [.russian: "уже есть", .english: "already there"],

        // Settings
        "settings.language": [.russian: "язык интерфейса", .english: "interface language"],
        "settings.pet": [.russian: "питомец", .english: "pet"],
        "settings.eggs": [.russian: "отсылки", .english: "easter eggs"],
        "settings.theme": [.russian: "тема", .english: "theme"],

        // Easter eggs — translated, never transliterated.
        "egg.unbreakable": [.russian: "неуязвимый", .english: "unbreakable"],
        "egg.horde": [.russian: "орда собралась", .english: "the horde has gathered"],
        "egg.eclipse": [.russian: "затмение", .english: "the eclipse"],
        "egg.shadowClone": [.russian: "теневое клонирование", .english: "shadow clone technique"],
        "egg.firstRule": [
            .russian: "первое правило: никто не входит по паролю",
            .english: "first rule: nobody logs in with a password",
        ],
        "egg.waitForIt": [.russian: "это будет… подожди…", .english: "it's gonna be… wait for it…"],
        "egg.legendary": [.russian: "…легендарно", .english: "…legendary"],
    ]
}
